Update instances.json
fosscord/fosscord-community-instances pull request #10
Opened 2021-10-02 01:48 UTC by Rednd

i chose to change my domain from discord to fosscord (removing the discord domain once this change is made to the website) just to make it a bit more "neat", and also changed the name and description a little

2021-10-02 19:44 UTC, xNaCly commented
![image](https://user-images.githubusercontent.com/47723417/135729917-c17922ca-253f-4e17-a6d5-989ebfc4c776.png)

2021-10-02 19:44 UTC, xNaCly requested changes
fix your page

2021-10-02 19:50 UTC, Rednd commented
sorry i was a bit busy, but it's back up, and is usually always up

2021-10-03 07:00 UTC, Intevel approved these changes

2021-10-03 12:24 UTC, Flam3rboy approved these changes

2021-10-03 13:03 UTC, xNaCly approved these changes

2021-10-03 13:03 UTC, merged